
def print_wave_file_header(wav):
    print("Chunk Id", wav.chunk_id)
    print("Chunk Size", wav.chunk_size)
    print("Format", wav.format)
    print("Sub Chunk 1 Id", wav.subchunk_1_id)
    print("Sub Chunk 1 Size", wav.subchunk_1_size)
    print("Audio Format", wav.audio_format)
    print("Num Channels", wav.num_channels)
    print("Sample Rate", wav.sample_rate)
    print("Byte Rate", wav.byte_rate)
    print("Block Align", wav.block_align)
    print("Bits Per Sample", wav.bits_per_sample)
    print("Sub Chunk 2 Id", wav.subchunk_2_id)
    print("Sub Chunk 2 Size", wav.subchunk_2_size)
    print('Bytes Per Sample', wav.bytes_per_sample)
